console.log("start try catch");
try {
  console.log(hey);
} catch (err) {
  console.log(err);
}
console.log("end try catch");
